### ISSUE TITLE
Babel 6 module.exports syntax

### ISSUE THREAD

**Issue by dtothefp** [webpack-contrib/expose-loader#14]
With the introduction of Babel 6 it seems that the `expose`d syntax has changed, and now instead of receiving the item exported by `export default` an Object is received with a `default` key. Assuming it has to do with

http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default
https://phabricator.babeljs.io/T2212

<img width="236" alt="screen shot 2016-01-04 at 4 14 22 pm" src="https://cloud.githubusercontent.com/assets/4656726/12100664/570d7362-b2fe-11e5-84eb-c547c97d5b5d.png">

``` js
  const babelrc = `{
    "presets": ["react", "es2015", "stage-0"],
    "env": {
      "development": {
        "plugins": [
          "rewire",
          "transform-runtime",
          "transform-decorators-legacy",
          "typecheck",
          ["react-transform",
            {
            "transforms": [{
              "transform": "react-transform-hmr",
              "imports": ["react"],
              "locals": ["module"]
            }, {
              "transform": "react-transform-catch-errors",
              "imports": ["react", "redbox-react"]
            }]
          }]
        ]
      },
      "production": {
        "plugins": [
          "transform-runtime",
          "transform-decorators-legacy",
          "typecheck"
        ]
      }
    }
  }`;
```

**Comment by lananelson** [comment]
@dtothefp did you find a way around this issue?

**Comment by titoasty** [comment]
After a long search and testing of multiple loaders, I've found these solutions :

## First solution :
Replace
`export default myObject`
by
`module.exports = myObject`

and so the expose loader works :)


## Second solution :
If you don't mind about namespaces, I also found another trick :
First create a file where you import all the files you need

```
import Cache from './Cache';
import Loader from './Loader';

module.exports = {
	Cache,
	Loader,
};
```

then import this file this way :
`import 'expose?Util!./utils.js';`

Now Cache and Loader classes will be available globally with the namespace Util.
(you can use Util.Cache & Util.Loader everywhere).

The two solutions uses the old `module.exports` style, directly and indirectly.
If you find anything else, I'll be glad to hear.

Hope it will help !

**Comment by Zache** [comment]
Did you try the ```add-module-exports``` plugin for babel?

**Comment by reglisse44** [comment]
Hi I have the same problem. I would like to export a angular module by this way:
`export default angular.module('app', []);`
but I have the default key which contain my angular module instead of just have my angular module :/

**Comment by qieqing** [comment]
I resolved the same problem by `add-module-exports` plugin, thx
