### ISSUE TITLE
Not able to expose the variable with dot in its name

### ISSUE THREAD

**Issue by TylerYang** [webpack-contrib/expose-loader#19]
Hi guys, let's say I have a js file with dot in its name, e.g `xyz.template.js`.  And I want to expose it into my global variable `modules` => `modules['xyz.template.js']`.

According to the [source code](https://github.com/webpack/expose-loader/blob/v0.7.1/index.js#L7) below(`value.split(".")`),  it is not possible to expose a variable which name contains 'dot'. I think it should be able to do that, 

``` javascript
 function accesorString(value) {
    var childProperties = value.split(".");  // Not able to expose 'xyz.template'  
    var length = childProperties.length;
    var propertyString = "global";
    var result = "";

    for(var i = 0; i < length; i++) {
        if(i > 0)
            result += "if(!" + propertyString + ") " + propertyString + " = {};\n";
        propertyString += "[" + JSON.stringify(childProperties[i]) + "]";
    }

    result += "module.exports = " + propertyString;
    return result;
}
```

Please correct me if I was wrong about this.

**Comment by evisong** [comment]
According to source code, it becomes `modules['xyy']['template']['js']`
