### ISSUE TITLE
Please provide example for Webpack 2 syntax

### ISSUE THREAD

**Issue by dschissler** [webpack-contrib/expose-loader#21]
For example something like this.  It would be very helpful if two Webpack 2 examples could be given for something like this with 1 and 2 exposes.

``` javascript
{
  test: /jquery\.js$/,
  loader: "expose?jQuery!expose?$"
}
```

**Comment by crucialfelix** [comment]
It seems to be this:

```js
      {
        test: require.resolve('jquery'),
        use: [
          {
            loader: 'expose-loader',
            query: 'jQuery'
          },
          {
            loader: 'expose-loader',
            query: '$'
          }
        ]
      }
```

at least I now have it building and window.jQuery and window.$ are there.

though I imagine they will change that. 'query' is only called that because of the `?` syntax. As an option, it isn't a query at all.

I expect they will change it to `options: { name: 'jQuery' }`

**Comment by evilebottnawi** [comment]
webpack@2 is outdated, please update webpack to latest version, thanks
