### ISSUE TITLE
Can't expose bluebird using `module.loaders` config in webpack.config.js.

### ISSUE THREAD

**Issue by d-ph** [webpack-contrib/expose-loader#22]
Hi,

For some reason I can't expose bluebird when using this config:

``` js
    module: {
        loaders: [
            { test: require.resolve('bluebird'), loader: 'expose?Promise' }
        ]
    }
```

but everything's fine, when I expose it inline like this:

``` js
require('expose?Promise!bluebird');
```

Do I do anything obviously wrong here?

I prepared a mini-project, that shows the problem: [link](http://www.megafileupload.com/buV5/expose-loader-debug.zip).
1. Unzip
2. `npm install`
3. `npm run webpack`
4. Open index.html
5. Open dev tools in the browser and run this in console: `Promise.version`. It should return a string.
6. Go back to the source code. Comment out the first line in `src/app.js` and uncomment the other line.
7. Uncomment the line `webpack.config.js`.
8. Open index.html.
9. Run this in js console: `Promise.version`.

Result: It's undefined. Bluebird hasn't been exposed to the global namespace (Chrome uses the native `Promise`).

Thanks.

**Comment by ErikSchierboom** [comment]
I have the exact same issue. Any ideas?

**Comment by MichaelBuen** [comment]
use webpack.ProvidePlugin

```typescript


const plugins = [
    new webpack.NamedModulesPlugin(),
    new HtmlWebpackPlugin({
        title: 'Ssk',
        filename: 'index.html',
        template: '../template/index.html',
        // chunksSortMode: 'dependency'
    }),
    new webpack.ProvidePlugin({
        'Promise': 'bluebird'
    })
];


const config = {
    context: path.join(__dirname, 'front-end'),
    entry: entries,
    output: {
        path: path.join(__dirname, 'dist--front-end'),
        filename: '[name].js',
        chunkFilename: '[name].chunk.js'
    },
    // Enable sourcemaps for debugging webpack's output.
    devtool: 'source-map',
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx'],
        // modules: ['front-end', 'node_modules']
    },
    plugins: plugins,
    module: {
        rules: rules
    },
    devServer: {
        historyApiFallback: {
            index: '/index.html'
        }
    }
};

module.exports = config;

```

Test code:

```typescript
// noinspection TsLint
console.log(`bluebird is${!!(Promise as any)['promisifyAll'] ? '': ' not'} available`);
```

Output:

![image](https://user-images.githubusercontent.com/1811636/37864969-e3900b7a-2fb0-11e8-8cfc-234f42237bd6.png)

**Comment by d-ph** [comment]
Thanks for your answer, Michael.

I'm closing this ticket because I now use a separate ts/js file where I import all js polyfills I require for the browsers I support. I actually prefer this way of doing this because I can see at a glance what I polyfill in my project without rummaging through the webpack's config file.

Thanks again for your time, though. I appreciate it.
