### ISSUE TITLE
Issue with expose-loader

### ISSUE THREAD

**Issue by PVAngular** [webpack-contrib/expose-loader#23]
I have a react component which is written in ES6. I have used babel/webpack to transpile it and generate a index.js file. I noticed that the resulting React Component is wrapped in a function and I cannot use it externally. I am trying to use it a different angular controller. I am trying to use webpack expose-loader but I still see undefined for the locally scoped vars.

**webpack.config.js**(snippet)

```
    module: {
    loaders: [
        {
            test: /.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel',

            query: {
                presets: [ 'react', 'es2015']
            }
        },
        {
            test: require.resolve("react"), loader: "expose?React" ,
            query: {
                presets: [ 'react', 'es2015']
            }
        }
    ]
}
}
```

WebPack (AppList is my react component)-Snippet

```
/***/ function(module, exports, webpack_require) {

'use strict';

var _react = __webpack_require__(2);

var _react2 = _interopRequireDefault(_react);

var _reactDom = __webpack_require__(36);

var _reactDom2 = _interopRequireDefault(_reactDom);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var AppList = _react2.default.createClass({
    displayName: 'AppList',

    propTypes: {},

    render: function render() {
        return _react2.default.createElement(
            'div',
            null,
            'appList '
        );
    }
});
module.exports = AppList;
/***/ },
```

Can anyone please help here?

**Comment by SpaceK33z** [comment]
I would suggest to use `ProvidePlugin`:

```js
plugins: [
  new webpack.ProvidePlugin({
    'React': 'react'
  })
]
```

For better help I would suggest to use StackOverflow.

**Comment by SpaceK33z** [comment]
Did you find a fix to your issue @PVAngular?

**Comment by cap-Bernardito** [comment]
Please update the dependencies to the latest versions. If the problem still appears, open a new issue with a minimally reproducible repository.
