### ISSUE TITLE
Expose after imports does not work, plugins order issue

### ISSUE THREAD

**Issue by artyomtrityak** [webpack-contrib/expose-loader#27]
Webpack v1.13.3

## OK

This does work and `this` inside Backbone becomes window.
```js
{ test: /backbone/, loader: 'imports?this=>window,$=jquery,_=underscore' },
```
Compiled source:
```js
...
	}).call(undefined);
	}.call(window));
```

## Error

This does now work because `this` inside Backbone is undefined.
```js
{ test: /backbone/, loader: 'imports?this=>window,$=jquery,_=underscore!expose?Backbone' },
```
Compiled source (no second `}.call(window))`):
```js
...
	}).call(undefined);
```

## OK №2

If plugins order changed and expose put first it works

```js
{ test: /backbone/, loader: 'expose?Backbone!imports?this=>window,$=jquery,_=underscore' },
```

**Comment by klimashkin** [comment]
The same issue with exposing react
```
{ 
  test: require.resolve('react'),
  use: [{
  loader: 'expose-loader',
    options: 'React',
  }],
},
```
If it is not first loader then modules that require react might be invoked before react itself is required.

**Comment by cap-Bernardito** [comment]
Please update the dependencies to the latest versions. If the problem still appears, open a new issue with a minimally reproducible repository.
