### ISSUE TITLE
jQuery failed to expose after update to 0.7.2

### ISSUE THREAD

**Issue by chenxeed** [webpack-contrib/expose-loader#29]
Hi, I face these errors after I update my package to use `expose-loader` 0.7.2

<img width="604" alt="screen shot 2017-02-14 at 11 07 06 am" src="https://cloud.githubusercontent.com/assets/3530355/22913442/c1a4330e-f2a5-11e6-916d-95d77a3600d2.png">

I confirmed this because when I revert the version back to 0.7.1, it's working normally again, no errors.

Thank you!

**Comment by chenxeed** [comment]
FYI, this is my webpack config to expose jquery. It's still working on 0.7.1.

```
  { test : /jquery\.js$/, loader : 'expose-loader?$' },
  { test : /jquery\.js$/, loader : 'expose-loader?jQuery' },
```

**Comment by Boshen** [comment]
After 7ae08d1743701ab119997c7f2608ca625129854c
```
module.exports = global["$"] = require("-!/web/node_modules/expose-loader/index.js?jQuery!/web/node_modules/source-map-loader/index.js!/web/node_modules/jquery/dist/jquery.js");
```
becomes
```
module.exports = global["$"] = require("-!./jquery.js");
```
which breaks the build

**Comment by FeliciousX** [comment]
can confirm there's a breaking change..

```json
  { test : resolve.require('jquery'), loader : 'expose-loader?jQuery' },
  { test : resolve.require('jquery'), loader : 'expose-loader?$' },
```

the order matters.. the first one goes through but `$` does not.

doing this

```json
{ test: resolve.require('jquery'), loader: 'expose-loader?jQuery!expose-loader?$' }
```

also doesn't expose `$` as jquery .. order matters again.. strange

v

**Comment by stephencookdev** [comment]
This seems to be the case for all multiple aliases to one library (i.e., does not just affect jQuery)

**Comment by jvmccarthy** [comment]
Yes, I think what's going on here is that the fix in #28 doesn't account for other loaders to be used in sequence. In my case, I have to shim a module with both exports and expose loaders in sequence. I think when the path was changed to relative, the other loader information was stripped off.

**Comment by cletusw** [comment]
This is also affecting my company. Temporarily pinned our build at v0.7.1

**Comment by d3viant0ne** [comment]
@rowanhill @jimbolla - Please pick up 0.7.3 and ping me back if you are still having issues. 

Anyone in the thread that has a public project throw up a link, i'm going to write some unit tests for this loader and I'd like to cover as many use cases as possible.

**Comment by gdborton** [comment]
Let me know if I can help in any way with the tests. I wanted to add some to the original pr, but I didn't know if my approach was the best.

**Comment by jimbolla** [comment]
0.7.3 worked for me. Thanks.

**Comment by rowanhill** [comment]
@d3viant0ne I'm afraid my repo isn't public, but I'm happy to confirm that 0.7.3 has fixed things for me.

Thanks for responding so quickly!

**Comment by d3viant0ne** [comment]
Cool & no problem :)

**Comment by chenxeed** [comment]
Hi, I upgraded my package to 0.7.3 and it's fixed now, thanks a lot! I'll close this issue now.
