### ISSUE TITLE
0.7.2: webpack no longer traverses project

### ISSUE THREAD

**Issue by rowanhill** [webpack-contrib/expose-loader#32]
Hello! Apologies if I'm raising this in the wrong place, but my build has started failing, and it looks like it's related to the recent 0.7.2 release of expose-loader.

FWIW, my build is now failing because UglifyJS is claiming there's a syntax error, specifically `Unexpected token: punc({)`.

I think that's a bit of a red herring, though: UglifyJS is choking on an `export {Foo} from './bar'` line in the JS that webpack is producing when I used 0.7.2, but which is absent when I use 0.7.1. In fact, when I use 0.7.2, webpack seems to be emitting only a single module, which is my Scripts/index.ts (which contains the exports that UglifyJS doesn't like); when I use 0.7.1, webpack seemingly correctly traverses the project from index.ts and emits all the modules I'd expect from my project.

My only use of expose-loader is in the single entry point I have in webpack.config.js:
```javascript
{
    entry: {
        myproj: 'expose?Myproj!./Scripts'
    }
}
```
I'm not especially familiar with webpack, so please let me know if you need any more information from me to diagnose this, or if you think my webpack config is inherently wrong in some way!

Thanks,
Rowan

**Comment by d3viant0ne** [comment]
Consolidating conversation to #29
