### ISSUE TITLE
what is wrong with this webpack2 expose-loader config?

### ISSUE THREAD

**Issue by w-** [webpack-contrib/expose-loader#40]
I am attempting to consume react-handsontable which recommends using expose-loader to make some dependencies available on the global scope.
https://github.com/handsontable/react-handsontable/wiki/Installation-guide#hot-ce-webpack

I have this issue 
https://github.com/handsontable/react-handsontable/issues/11

which may just be my ignorance in configuring expose-loader.

from the issue above:
relevant part of webpack config looks like

>      {
>         test: require.resolve('handsontable'),
>         loader: 'expose-loader?Handsontable'
>       },
>       {
>         test: require.resolve('numbro'),
>         loader: 'expose-loader?numbro',
>         //options: {'numbro': null}
>       },
>       {
>         test: require.resolve('moment'),
>         loader: 'expose-loader?moment'
>       },
>       {
>         test: require.resolve('pikaday'),
>         loader: 'expose-loader?Pikaday'
>       },
>       {
>         test: require.resolve('zeroclipboard'),
>         loader: 'expose-loader?ZeroClipboard'
>       },

inside the relevant react component I import as outlined by the docs:

```js
import moment from 'moment';
import numbro from 'numbro';
import pikaday from 'pikaday';
import Zeroclipboard from 'zeroclipboard';
import Handsontable from 'handsontable';
import HotTable from 'react-handsontable';
import 'handsontable/dist/handsontable.full.css';
```

but if i do window.numbro I can see that it is undefined. 

If i understand correctly, i expect window.numbro to be my numbro import. Is this correct?
If yes, what is going wrong?
if not, how do i test that expose-loader is doing what it should be doing?

**Comment by redler** [comment]
Does it work if you try it in your code directly, with something like `require('expose-loader?moment!moment`?

**Comment by kaizencodes** [comment]
Try to use this format https://github.com/webpack-contrib/expose-loader/issues/21#issuecomment-263545579

so instead of 
```
{
    test: require.resolve('handsontable'),
    loader: 'expose-loader?Handsontable'
},
```
try this:
```
{
    test: require.resolve('handsontable'),
    use: {
      loader: 'expose-loader',
      query: 'Handsontable'
    }
},
```

**Comment by w-** [comment]
@redler  and @kaizencodes .

Unfortunately neither work. I've given up on using the handsontable react library so haven't pursued much more than i already have.

**Comment by michael-ciniawsky** [comment]
@w- You could you take a look at `imports-loader` maybe. I don't know how handsontable etc exports their code, maybe `exports-loader` simply can't load that. Sry for the inconvenience here, we are working on improving and documenting things like that better in the near future 🙃
