### ISSUE TITLE
how to expose to inline script?

### ISSUE THREAD

**Issue by bonesoul** [webpack-contrib/expose-loader#47]
i've a bundle and some functions and i want to be able to expose them to my inline html <script> tag. is it even possible?

**Comment by ianlofs** [comment]
I have the exact same use case. Trying to convert a legacy code base that has quite a few of inline html script tags which rely on vendor code.

**Comment by evilebottnawi** [comment]
Yes, just put your old `script` after old packages, like:
```html
<scripts src="./path/to/bundle.js"></script>
<scripts src="./vendor.js"></script>
```

You need to run bundle files firstly, otherwise webpack doesn't fill expose object to global this.
