### ISSUE TITLE
Does not work on Windows 10 OS?

### ISSUE THREAD

**Issue by hjlld** [webpack-contrib/expose-loader#48]
First here's my webpack.config.js:

```
        test: /assets\/lib\/babylon.js/,
        use: [
          {
            loader: 'expose-loader',
            query: 'BABYLON'
          }
        ]
```

Then I found a weird thing, with a totally same project and its code:

- After building on Windows 10 OS,  window.BABYLON is not defined.
- But after building on Mac or Linux,  window.BABYLON is OK.

**Comment by evilebottnawi** [comment]
@hjlld please create minimal reproducible test repo, thanks!

**Comment by hjlld** [comment]
@evilebottnawi sorry for my late reply. Try this repo:

https://github.com/hjlld/expose-example

1. npm install 
2. npm run build

**Comment by gbellini79** [comment]
We just had the same problem.
On Windows apparently the file path comes with \ instead of /. So in your RegEx you should handle both cases as: /assets[\\\\\\/]lib[\\\\\\/]babylon\\.js$/
(http://regexr.com/3geks)

**Comment by timse** [comment]
I assume this can be closed?
Given the loader can't do anything about how webpack handles the test-regexp, and the above mentioned regexp just doesnt match under windows?

**Comment by michael-ciniawsky** [comment]
Yep you're right, good catch @hjlld see @timse's [comment](https://github.com/webpack-contrib/expose-loader/issues/48#issuecomment-348666369)
