### ISSUE TITLE
Compatibility with webpack/webpacker 3?

### ISSUE THREAD

**Issue by niedfelj** [webpack-contrib/expose-loader#54]
This doesn't appear to be working correctly with the latest webpacker/rails setup, has it been tested with webpack 3? We are using the require format like this:

require('expose-loader?$!jquery')

And not seeing a global $ defined

**Comment by liz-mars** [comment]
This specific issue just caused me to waste three hours, so it would be good to either fix the bug, deprecate this package, or put a warning on the README.

**Comment by IEfucker** [comment]
webpack3.8.1
came up with the same issue

**Comment by aratcliffe** [comment]
Same on webpack 3.8.1

**Comment by 116050423** [comment]
same on "webpack": "^3.6.0",

**Comment by febeling** [comment]
This `require('expose-loader?$!jquery')` should do it on its own.

To configure the expose-loader in config, I use this (feather-icons in this case):
```
environment.loaders.append('expose', {
  test: require.resolve('feather-icons'),
  use: [{
    loader: 'expose-loader',
    options: 'feather'
  }]
})
```
and then just the import:
```
import 'feather-icons';
```

**Comment by evilebottnawi** [comment]
We fixed a lot of bug for the next release, so it should be work, if you will faced with issue again please open a new issue with reproducible test repo, thanks
