### ISSUE TITLE
Setup via `webpack.config.js` file not working with NamedModulesPlugin

### ISSUE THREAD

**Issue by WiseBird** [webpack-contrib/expose-loader#55]
Reproduction - https://github.com/WiseBird/expose_loader_named_modules_plugin

I use `expose-loader` to expose jquery:
```
            {
                test: require.resolve('jquery'),
                use: [{
                    loader: 'expose-loader',
                    options: 'jQuery'
                }]
},
```

It works without `NamedModulesPlugin` while producing next output:
```
/* 88 */
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["jQuery"] = __webpack_require__(89);
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(1)))

/***/ }),
/* 89 */
/***/ (function(module, exports, __webpack_require__) {

var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;/*!
 * jQuery JavaScript Library v3.2.1
...
```

when `NamedModulesPlugin` is included output is following:
```
/***/ "./node_modules/jquery/dist/jquery.js":
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["jQuery"] = __webpack_require__("./node_modules/jquery/dist/jquery.js");
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__("./node_modules/webpack/buildin/global.js")))

/***/ }),

/***/ "./node_modules/jquery/dist/jquery.js":
/***/ (function(module, exports, __webpack_require__) {

var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;/*!
 * jQuery JavaScript Library v3.2.1
```

So both modules: the one exposing jquery and the one containing jquery have the same name.

Moreover when exposing via `require('expose-loader?jQuery!jquery');` the module exposing jquery have different name:
```
/***/ "./node_modules/expose-loader/index.js?jQuery!./node_modules/jquery/dist/jquery.js":
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["jQuery"] = __webpack_require__("./node_modules/jquery/dist/jquery.js");
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__("./node_modules/webpack/buildin/global.js")))

/***/ }),
```

`NamedModulesPlugin` [uses](https://github.com/webpack/webpack/blob/6cad87f5fecc0db52a0a0211beb64c68eda2cadb/lib/NamedModulesPlugin.js#L17) [`libIdent`](https://github.com/webpack/webpack/blob/c8fd542579c554409eb1202866755fa7be0bad51/lib/NormalModule.js#L91) from `NormalModule` that in its order uses `userRequest` that differs when library exposed via config file or via require statement.

**Comment by sokra** [comment]
That's a bug in `libIdent` webpack/webpack.

**Comment by WiseBird** [comment]
@sokra Should I refile it there?

**Comment by ypconstante** [comment]
Some other issues related this bug:
- webpack/webpack#4613
- webpack-contrib/expose-loader#49
- webpack-contrib/extract-text-webpack-plugin#648

The extract-text-webpack-plugin issue was fixed, maybe the fix is similar.

**Comment by cansin** [comment]
Actually the problem `expose-loader` encountering might be different from what `extract-text-webpack-plugin` is having (based on https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/648#issuecomment-337031831 ).

**Comment by cansin** [comment]
So a patch to `webpack/webpack` (as described at https://github.com/webpack/webpack/issues/4613#issuecomment-342694095 ) "fixes" this issue. But I think such a patch would also mess up with the consistent hashing for long-term caching since for the modules skipped hashing would be non-deterministic (I think). But I am not sure. I am hoping @sokra would weigh in.

**Comment by timse** [comment]
just saw this after opening #58 sorry for that :P.

The issue probably should be handled by webpack?

**Comment by cansin** [comment]
@timse thanks for https://github.com/webpack-contrib/expose-loader/pull/58 ! That would at least unblock everyone while the underlying issue gets fixed at https://github.com/webpack/webpack .
