### ISSUE TITLE
[Refactor] Support exposing ESM without `harmony` export

### ISSUE THREAD

**Issue by benirose** [webpack-contrib/expose-loader#56]
I'm using expose-loader to expose some ES6 modules, which are currently using `export default {...}`, however instead of getting the resource at my exposed variable, it's at `module.default`. Here's my require:
```javascript
require("expose-loader?Store!./store/index.js");
```

And here's my export:
```javascript
export default new Vuex.Store({
...
})
```

My module is now exposed at `Store.default`.

Is this just a side effect of ES6 modules or is there a way to expose the default directly on the variable?

**Comment by michael-ciniawsky** [comment]
No the loader still uses CJS [internally](https://github.com/webpack-contrib/expose-loader/blob/master/index.js#L20) so your exposed file becomes a `harmony` export atm. We could/should update this to use ESM instead, but needs triage

**Comment by michaelord** [comment]
Is there any work around for this issue? I've refactored code today and this issue has reared its head for me...

**Comment by patrick-mcdougle** [comment]
@michael-ciniawsky how does #85 look? Will this solve this issue?
