### ISSUE TITLE
0.7.4 not compatible with webpack v1

### ISSUE THREAD

**Issue by amakhrov** [webpack-contrib/expose-loader#63]
Looks like in the recent 0.7.4 release `peerDependencies: {"webpack": "^2.0.0 || ^3.0.0"}` has been added - effectively marking the plugin incompatible with webpack v1.

Is there any change in the code that really makes the module incompatible with v1? It doesn't seem to be the case based on the diff (https://github.com/webpack-contrib/expose-loader/compare/v0.7.3...v0.7.4) - but maybe I'm missing something?
Also the readme file still contains instructions for webpack v1 usage.

Is it possible to update peerDependencies to allow webpack v1?

**Comment by evilebottnawi** [comment]
webpack@1 is outdated, please update webpack to latest version, thanks
