### ISSUE TITLE
webpack 4

### ISSUE THREAD

**Issue by 719media** [webpack-contrib/expose-loader#66]
is this module going to be updated for use with webpack 4 with #61  ?

**Comment by michael-ciniawsky** [comment]
@719media Besides the` peerDependency` warning, did you use `expose-loader` with `webpack >= 4`? Could you confirm nothing broke ? I will patch the package then :)

**Comment by craigjennings11** [comment]
Nothing broke in my project when I upgraded to webpack@4.0.0. Just got the warning.

**Comment by basilikum** [comment]
For me expose-loader@0.7.1 stopped working when updating to webpack@4.1.0. I could not see an error message but it failed to bind jquery to window, using the following configuration:

```javascript
{
    test: require.resolve('jquery'),
    use: [{
        loader: 'expose-loader',
        options: 'jQuery'
    },{
        loader: 'expose-loader',
        options: '$'
    }]
}
```

The most recent version (0.7.4) however seems to work fine.

**Comment by zapo** [comment]
Works fine as well for us in development. 

But for some reason tests (ran with karma & karma-webpack) seems to no longer have access to exposed modules. I'm running them in "development" mode with no automagic vendor chunk splitting. Not sure if expose-loader concern or not.

```
  Uncaught ReferenceError: jQuery is not defined
```

**Comment by michael-ciniawsky** [comment]
Waiting for #61 and patch asap

**Comment by michael-ciniawsky** [comment]
Released in [`v0.7.5`](https://github.com/webpack-contrib/expose-loader/releases/tag/v0.7.5) 🎉

**Comment by nass600** [comment]
Looks like this is still happening.

webpack: 4.6.0
expose-loader: 0.7.5

**Comment by Trainmaster** [comment]
@zapo Did you find a solution for the failing tests running with karma & karma-webpack?

**Comment by eerrecalde** [comment]
Still happening to me :/

webpack: 4.19.1
expose-loader: 0.75

This (in my entry file) works fine: 

```import "expose-loader?$!jquery";
import "expose-loader?jQuery!jquery";```

With this (in my webpack.config) doesn't work: 
```{
test: require.resolve('jquery'),
            use: [
              {
                loader: 'expose-loader',
                options: 'jQuery'
              },
              {
                loader: 'expose-loader',
                options: '$'
              }
            ]
}
```

**Comment by eerrecalde** [comment]
Any update about this @michael-ciniawsky?

**Comment by DaleyKD** [comment]
Any update on this?  I'm on webpack 4.41.2 and expose-loader 0.7.5.
