### ISSUE TITLE
The react-router-dom,react-redux,redux is packaged invalid in webpack V3.

### ISSUE THREAD

**Issue by ghost** [webpack-contrib/expose-loader#68]
When a package is exposed as a global variable in the react project, the same configuration react-router-dom,react-redux, and redux are not valid when packaged.
Attach a code:
`
module: {
    rules: [
      {
        test: /\.(js|jsx|es6)$/,
        exclude: /node_modules/,
        use: 'babel-loader'
      },
      {
        test: /\.less$/,
        use: ['style-loader', 'css-loader', 'postcss-loader', 'less-loader']
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader', 'postcss-loader']
      },
      {
        test: /\.(jpg|jpeg|gif|bmp|png)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 8192,
            name: 'assets/images/[name].[ext]'
          }
        }
      },
      {
        test: /\.(woff|woff2|eot|svg|ttf)($|\?)/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 8192,
            name: 'assets/fonts/[name].[ext]'
          }
        }
      },
      {
        test: require.resolve("react"),
        use: [
          {
            loader: 'expose-loader',
            options: 'React'
          }
        ]
      },
      {
        test: require.resolve("react-addons-pure-render-mixin"),
        use: [
          {
            loader: 'expose-loader',
            options: 'PureRenderMixin'
          }
        ]
      },
      {
        test: require.resolve("react-router-dom"),
        use: [
          {
            loader: 'expose-loader',
            options: 'ReactRouter'
          }
        ]
      },
      {
        test: require.resolve("react-redux"),
        use: [
          {
            loader: 'expose-loader',
            options: 'ReactRedux'
          }
        ]
      },
      {
        test: require.resolve("redux"),
        use: [
          {
            loader: 'expose-loader',
            options: 'Redux'
          }
        ]
      },
      {
        test: require.resolve("react-dom"),
        use: [
          {
            loader: 'expose-loader',
            options: 'ReactDom'
          }
        ]
      }
    ]
  }
`
Excuse me what method solves, what reason causes?

**Comment by evilebottnawi** [comment]
Issue is not readable, sorry, I can't help, we prepare the next big release with a lot of fixes, maybe it help, ETA is the end of week, if you faced with the problem again after update feel free to open a new issue with reproducible test repo, sorry for delay
