### ISSUE TITLE
Expose Order?

### ISSUE THREAD

**Issue by jeffling** [webpack-contrib/expose-loader#7]
I have a common bundle like this: 

`common: ['expose?jQuery!jquery', 'expose?angular!angular', 'angular-ui-router', 'angular-animate', 'angular-sanitize']`

I also extend it like `new webpack.optimize.CommonsChunkPlugin 'common', 'common/common.js'`

It seems like angular isn't exposed before angular-ui-router runs, causing an error. 

Taking everything angular-related out of the common bundle and using ProvidePlugin works for some reason, but I would like to have an explicit common bundle.

**Comment by grofit** [comment]
I have a similar issue where where I am exposing knockout and knockout validation but the validation aspect does not seem to link to the underlying ko instance.
