### ISSUE TITLE
Expose Loader not exposing all attributes

### ISSUE THREAD

**Issue by rahiparikh** [webpack-contrib/expose-loader#74]
Expose Loader does not correctly expose all the attributes of a module.

This issue is for a:

- [X] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
https://codesandbox.io/s/nw4pk93jm - The sample shows the case where, when a module made available without webpack/expose-loader, all the properties/functions are available. 

https://codesandbox.io/s/l9q9z541k9 - The sample shows the case where, when a module made available with webpack/expose-loader, only some properties/functions are available.

### Expected Behavior
Same/All attributes should be available with and without Webpack/Expose-loader.

**Comment by cap-Bernardito** [comment]
A same problem #56. Will be fixed there.

**Comment by cap-Bernardito** [comment]
In your case, this is not an expose-loader bug. You write:

```js
import openpgp from 'openpgp';
```

In this case, the default export from `openpgp` package is placed in the variable 'openpgp'. And these are not all options.

To export all the options you need to write:

```js
import * as openpgp from 'openpgp';
```
