### ISSUE TITLE
splitChunks won't expose given expose-loader rules

### ISSUE THREAD

**Issue by juanitopons** [webpack-contrib/expose-loader#81]
* Operating System: Linux Ubuntu 16
* Node Version: v8.12.0
* NPM Version: 6.6.0
* webpack Version: 4.29
* expose-loader Version: 0.7.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js (splitchunks)

```js
  optimization: {
    noEmitOnErrors: true,
    nodeEnv: 'development',
    runtimeChunk: 'single',
    splitChunks: {
      chunks(chunk) {
        return mainLayouts.includes(chunk.name);
      },
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors-layout',
          enforce: true,
        },
      }
  }
```
##### webpack.config.js (expose-loader rules)

```js
  {
        test: require.resolve('jquery'),
        use: [{
          loader: 'expose-loader',
          options: 'window.jQuery',
        },
        {
          loader: 'expose-loader',
          options: 'jQuery',
        }, {
          loader: 'expose-loader',
          options: '$',
        }],
    }
```
### Expected Behavior

When I splitchunks for vendors (ej. jquery) and add this bundle to my template as well as its own template bundle, globals variables are not accesible.
If I DON'T splitChunks, expose-loader exports correctly the variable. I'm getting crazy wondering what the hell I'm doing bad.

I have 4 templates chunks with its own bundle, and I wanted to extract common libraries to a vendros-layout bundle. I managed to splitted but the things seem to change.

### Actual Behavior

jQuery is not accesible when splitt vendors bundle. If I do not split it, jQuery is accesible in the same layout it was not on the split process.

### How Do We Reproduce?
templateA.pug --> vendors-layout.js (splitted bundle), templateA-bundle.js (specific template bundle)
templateB.pug -> vendors-layout.js (splitted bundle), templateB-bundle (specific template bundle)
templateA.js -> require('jquery'), requires of specific libraries for template (some use jQuery global expose)
templateB.js -> require('jquery'), requires of specific libraries for template (some use jQuery global expose)

With split strategy of Webpack 4, vendors-layout won't expose correctly jQuery, and because of that next bundle libraries won't be able to access jQuery variable on the scope.
Disabling vendors-layout it works.

**Comment by doktordirk** [comment]
try to exclude jquery from `test: /[\\/]node_modules[\\/]/,`
