### ISSUE TITLE
Exposing ES6 modules without the default property

### ISSUE THREAD

**Issue by stefanfrede** [webpack-contrib/expose-loader#87]
Is there any news regarding exposing ES6 modules without the default property?

I searched now for quite some time, and the only thing I can find is the workaround with `module.exports = …`.

**Comment by patrick-mcdougle** [comment]
I think my code that I have open for review linked above solves this problem. I am not using it in production and it's my first webpack contribution, so use at your own risk.

**Comment by cap-Bernardito** [comment]
A same problem #56. Will be fixed there.
