### ISSUE TITLE
expose-loader not working correctly with webpack 4

### ISSUE THREAD

**Issue by jwlms** [webpack-contrib/expose-loader#99]
- Operating System: macOS 10.14.6
- Node Version: 12.18.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- expose-loader Version: 0.7.5

### Expected Behavior

Requiring `expose-loader` and running webpack should bundle JavaScripts.

### Actual Behavior

Requiring `expose-loader` and running webpack does not bundle JavaScripts, but throws an error:

```bash
Module build failed (from /Users/joshua/Projects/Work/repos/project_name/node_modules/expose-loader/index.js):
TypeError: this.query.substr is not a function
```

### How Do We Reproduce?

```js
import 'expose-loader?jQuery!jquery';
```

I put in a corresponding [Pull Request here](https://github.com/webpack-contrib/expose-loader/pull/98/files), however I am a bit unsure as to how to go about testing this.

**Comment by evilebottnawi** [comment]
Fixed in the master

**Comment by asfaltboy** [comment]
Thanks for the quick fix @evilebottnawi 🎉 ! Can we tentatively expect a 0.7.6 release sometime this week?

**Comment by evilebottnawi** [comment]
ETA (`1.0.0`) at this week

**Comment by asfaltboy** [comment]
Hey @evilebottnawi , any news on the release? Is there anything we can do to help test or update any files?

**Comment by evilebottnawi** [comment]
@asfaltboy Hello, small delay, ETA is today, more improvements and fixes

**Comment by jwlms** [comment]
@asfaltboy Great that you're on it so quickly. What is the corresponding commit for the fix you've already created?

**Comment by evilebottnawi** [comment]
@jwlms It was big refactor with many fixes, hard to say which commit to fix your problem

**Comment by jwlms** [comment]
@evilebottnawi - I didn't verify it was fixed, but was just going off of that comment implying that it was already fixed at the time I forked and made a PR. Looking at the source it seems like this non-es function is still being used here as outlined in the PR I put in: https://github.com/webpack-contrib/expose-loader/blob/master/test/helpers/readAsset.js#L13

I don't know why webpack was throwing the error (given it's location in `test/helpers`), but it does seem odd to be using such a legacy function that isn't part of the core language: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

Just curious to what was happening as I've already came up with an alternative to using expose-loader.

**Comment by evilebottnawi** [comment]
@jwlms If you still have a problem please open a new issue with reproducible test repo
